name: 'intergatecicd'
description: 'Deploys .nupkg packages in the Github workspace directory to UiPath Orchestrator'

env:
  ORCHESTRATOR_URL: ${{ secrets.ORCHESTRATOR_URL }}
  ORCHESTRATOR_TENANT: ${{ secrets.ORCHESTRATOR_TENANT }}
  ORCHESTRATOR_FOLDER: ${{ secrets.ORCHESTRATOR_FOLDER }}
  ORCHESTRATOR_APP_ID: ${{ secrets.ORCHESTRATOR_APP_ID }}
  ORCHESTRATOR_APP_SECRET: ${{ secrets.ORCHESTRATOR_APP_SECRET }}

runs:
  using: "composite"
  steps:    
    - name: Deploy
      shell: powershell
      run: uipcli package deploy "${{ github.workspace }}" "$ORCHESTRATOR_URL" "$ORCHESTRATOR_TENANT" --accountForApp "$ORCHESTRATOR_APP_ID" --applicationSecret "$ORCHESTRATOR_APP_SECRET" --organizationUnit "$ORCHESTRATOR_FOLDER"
